In [1]:
import pandas as pd
import numpy as np

In [2]:
#Extracting data its features and labels
data = pd.read_csv('iris.data', sep=',')
print(data.shape)
data


(150, 5)


Sepal Length  Sepal Width  Petal Length  Petal Width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [16]:
#Taking X for WX + b in matrix form
inp_features = data.iloc[:, :4].values # as a numpy matrix
print(type(inp_features))
inp_features

<class 'numpy.ndarray'>


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
op_label = data['Species'] # as a single dataframe series
print(type(op_label))
print(op_label.shape)
op_label.unique()

<class 'pandas.core.series.Series'>
(150,)


array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
# Implementing (hypothetical)sigmoid fucntion
def sigmoid(W, X):
    # here X is a pandas series, thus no shape imcompatibility
    # X : (150 X 5)
    # W : (1 X 5)
    z = np.dot(W, X.T)
    fxn_z = 1 / (1 + np.exp(-z))

    return fxn_z

In [6]:
# Defining overall cost function
def cost_fxn(X, Y, W):
        Y1 = sigmoid(X, W) # Y1: predicted output
        J = -(1/len(X)) * np.sum(Y*np.log(Y1) + (1-Y)*np.log(1-Y1))
        return J

In [7]:
#Creating a dataframe for  output classes, of 150 X 3 
(m, n) = data.shape
Y1 = np.zeros([m, len(op_label.unique())])
Y1 = pd.DataFrame(Y1)
Y1.shape

(150, 3)

In [8]:
#Filling in classes 1/0 for op labels in Y1
for i in range(len(Y1)):

    for j in range(len(op_label.unique())):
        
        if op_label[i] == op_label.unique()[j]:
            Y1.iloc[i, j] = 1
        else:
            Y1.iloc[i, j] = 0
Y1.head()


0    1    2
0  1.0  0.0  0.0
1  1.0  0.0  0.0
2  1.0  0.0  0.0
3  1.0  0.0  0.0
4  1.0  0.0  0.0

In [9]:
X = pd.DataFrame(inp_features)
X = pd.concat([pd.Series(1, index=X.index, name='bias'), X], axis=1) # Adding a column for bias 

print(X)
X.shape

     bias    0    1    2    3
0       1  5.1  3.5  1.4  0.2
1       1  4.9  3.0  1.4  0.2
2       1  4.7  3.2  1.3  0.2
3       1  4.6  3.1  1.5  0.2
4       1  5.0  3.6  1.4  0.2
..    ...  ...  ...  ...  ...
145     1  6.7  3.0  5.2  2.3
146     1  6.3  2.5  5.0  1.9
147     1  6.5  3.0  5.2  2.0
148     1  6.2  3.4  5.4  2.3
149     1  5.9  3.0  5.1  1.8

[150 rows x 5 columns]


(150, 5)

In [10]:

theta = np.zeros([X.shape[1], Y1.shape[1]]) # 5 X 3
print(theta.shape)
print(theta)
print(type(theta))


(5, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [11]:
def gradient_descent(X, y, theta, alpha, epochs):
    m = len(X)
    for i in range(0, epochs):

        for j in range(0, 3): # For each of the columns in Y1, we will implement a binary classification.
            theta = pd.DataFrame(theta)
            h = sigmoid(theta.iloc[:,j], X)

            for k in range(0, theta.shape[0]):# here 0 -> (4-1)
                theta.iloc[k, j] -= (alpha/m) * np.sum((h-y.iloc[:, j])*X.iloc[:, k]) # h:150 values

            theta = pd.DataFrame(theta)
    return theta

In [12]:
theta = gradient_descent(X, Y1, theta, 0.025, 3500)


In [13]:
prob_ls = []
for i in range(0, 3):
    
    theta1 = pd.DataFrame(theta)
    h = sigmoid(theta1.iloc[:,i], X) # Using the optimized weights to predict probability of 3 classes
    prob_ls.append(h)

prob_ls=pd.DataFrame(prob_ls)

In [14]:
accuracy = 0
for col in range(0, 3):
    for row in range(len(Y1)):
        
        if (Y1.iloc[row, col] == 1) and (prob_ls.iloc[col, row] >= 0.5):
            accuracy += 1

accuracy = accuracy / len(X) * 100
print(accuracy)

76.66666666666667
